modules:
- name: Database
  path: C:\Source\Database
  type: module
  packages:
  - Aderant.Database
  - Aderant.Libraries.Models
- name: Framework
  path: C:\Source\ExpertSuite\Framework
  type: module
  packages:
  - Aderant.Framework.Core
- name: Presentation
  path: C:\Source\Presentation
  type: module
  packages:
  - Aderant.Presentation.Core
- name: ExpertShare
  path: c:\expertshare
  type: target
- name: SharedBin
  path: C:\AderantExpert\Local\SharedBin
  type: target
pipelines:
- Framework => Query,Presentation,Customization,Billing,ExpertShare
- Presentation => Query,Customization,Billing,ExpertShare
